version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  lint:
    working_directory: /go/src/github.com/Adriel-M/gb
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: "Lint Go code"
          command: "diff -u <(echo -n) <(gofmt -d .)"
  unit-test:
    working_directory: /go/src/github.com/Adriel-M/gb
    docker:
      - image: circleci/golang:latest
    parameters:
      run-coverage:
        type: boolean
        default: false
    steps:
      - checkout
      - when:
          condition: << parameters.run-coverage >>
          steps:
            - run:
                name: "Unitests with coverage"
                command: "go test -race -coverprofile=unit-coverage.txt -covermode=atomic ./..."
            - codecov/upload:
                file: unit-coverage.txt
                flags: unittests
      - unless:
          condition: << parameters.run-coverage >>
          steps:
            - run:
                name: "Unittests"
                command: "go test ./..."

workflows:
  test:
    jobs:
      - lint
      - unit-test
  nightly:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                  - master
    jobs:
      - unit-test:
          run-coverage: true
